sampleFile: sampleTableESP.tsv
fastq_path: '/data/OGVFB_BG/EiaD_2019_05/'
bam_path: '/data/swamyvs/eyesplice_predictor/'
gtf: 'ref/gencodeAno_comp.gtf'
genome: 'ref/gencodePA.fa'
tx_fasta: 'ref/gencode_tx.fasta'
window_size: '40'
salmon_version: 'salmon/0.11.0'
stringtie_version: 'stringtie/1.3.4d'
STAR_version: 'STAR/2.6.1c'
rmats_verson: 'rmats/4.0.2'
R_version: 'R/3.5.2'
TransDecoder_version: 'TransDecoder/5.0.1'
samtools_version: 'samtools/1.9'
gffcompare_version: 'gffcompare/0.10.5'
hmmer_version: 'hmmer/3.2.1'
crossmap_version: 'crossmap/0.2.7'
working_dir: '/data/swamyvs/eyesplice_predictor'
deeptools_version: 'deeptools/3.1.3'
mosdepth_version: 'mosdepth/0.2.3'
bedtools_version: 'bedtools/2.27.1'
